baseURL = "https://guo-yu-chao.github.io/"
locale = "en-us"
title = "Yu-Chao Guo"
theme = "PaperMod"

[pagination]
pagerSize = 10

[params]
defaultTheme = "light"
disableThemeToggle = true
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = false
ShowBreadCrumbs = false
ShowCodeCopyButtons = false
homeInfoParams = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "research"
name = "Research"
url = "/research/"
weight = 20

[[menu.main]]
identifier = "publications"
name = "Publications"
url = "/publications/"
weight = 30

[[menu.main]]
identifier = "news"
name = "News & Blog"
url = "/news/"
weight = 40

[[menu.main]]
identifier = "cv"
name = "CV"
url = "/files/CV.pdf"
weight = 50

[params.assets]
customCSS = ["css/extended.css"]